### ISSUE TITLE
min() macro conflict

### ISSUE THREAD

**Issue by OlafvdSpek** [boostorg/convert#35]
```
strtol.hpp:
ch_type  str[sz] = {0}; std::strncpy(str, &*range.begin(), std::min(sz - 1, range.size()));

// boost\convert\strtol.hpp(209): error C2589: '(': illegal token on right side of '::'
```

I think this isn't properly guarded against Windows's macro named min. 
MSVC 15.8

**Comment by yet-another-user** [comment]
Yes, I believe you are correct suspecting the macro. Uh, the 'min' macro...
it brings so many "wonderful" memories. :-) It's not just Windows. The X11
windowing system still has it in X11/Xlibint.h...

That said, I am not sure if humble boost\convert\strtol.hpp is the place to
address the monumental clash of the OS macro and the C++ function. It
appears that such a fundamental problem might need to be addressed on a
higher level (and I expect it has) so that the user might need to include
some "compatibility.hpp" or "portability.hpp" in their code. For example,
on Linux I see the following done on the language levels:

/usr/include >> grep -r 'undef min' *
x86_64-linux-gnu/c++/7/bits/c++config.h:#undef min
x86_64-linux-gnu/sys/sysmacros.h:#undef minor

I'd expect to find something similar on Windows. What do you think?

**Comment by yet-another-user** [comment]
Paul, thank you for chiming in... and you are right of course... I suspect
I still have something like that somewhere in my code... How could I
forget?.. Will put the fix in... Or, maybe, just wait about 10 years for
Windows to die naturally... :-) Thanks again. Much appreciated.

**Comment by yet-another-user** [comment]
Olaf, I worked around the issue as per Paul's comments. I did not test it on MS Win (don't have it) but expect it all to be good. Please see if that is to your satisfaction. Tnx for pointing it out.

**Comment by OlafvdSpek** [comment]
Thanks!

BTW, boost::cnv::strtol::str_to_i() might benefit from an assert(!range.empty()) as it does an unchecked *range.begin().

**Comment by yet-another-user** [comment]
Thanks, Paul, for the pointer. Much appreciated. I'll keep your notes for
the next "horse" and try using the tools mentioned... Jeez, Boost is such a
huge trove of bits and pieces and tool and nuggets and everything...
Sometimes it feels like it is slowly sinking under its own weight. :-( Or,
maybe, I am just an old pessimist. Hope it is the latter.

**Comment by yet-another-user** [comment]
Olaf,
> BTW, boost::cnv::strtol::str_to_i() might benefit from an
> assert(!range.empty()) as it does an unchecked *range.begin()
I just checked the piece you mentioned and, yes, if the function was  public, the added assert() might be beneficial... although I'd think a simple return would be more appropriate... and that is exactly what the caller of that function -- cnvbase::str_to_(). Agree?

**Comment by OlafvdSpek** [comment]
I did see the caller and it's just a minor thing.. point is since it's a function, it could also be called from elsewhere.
